### ISSUE TITLE
can't decrypt backups created with OandBackupX 7.0.0

### ISSUE THREAD

**Issue by andrei-a-papou** [Tiefkuehlpizze/OABXDecrypt#1]
Thanks for the tool, it looks promising!

However, I couldn't get it to work with the current stable version of OAndBackupX (v7.0.0). The error is "invalid auth tag".

My suspicion is, we need the [original salt](https://github.com/NeoApplications/Neo-Backup/blob/bee23171beaac044bcb34e2b8371d832a9c4709c/app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt) to correctly derive the key from the password, am I right?

If so, is it possible to update your tool to decrypt the encrypted shared preferences and get the salt from there?

**Comment by andrei-a-papou** [comment]
Thanks for v1.1! I'm testing it right now, but no luck so far.

I'm confused about the property file a little. On my device (Android 11, OAndBackupX v7.0.0), I have an encrypted preferences file in XML format,  com.machiav3lli.backup.xml. Is this the one I need? Looks like it's encrypted with [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences).

Passing this file to the -prop option results in an error:

```
13:19:32.422 INFO: Assuming OABX/Neobackup 7 backup
Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:521)
	at org.json.JSONObject.<init>(JSONObject.java:225)
	at org.json.JSONObject.<init>(JSONObject.java:421)
	at tkp.NeoBackupProperties.<init>(NeoBackupProperties.java:15)
	at tkp.App.decryptFile(App.java:110)
	at tkp.App.main(App.java:197)
```

The file is in XML format, but the decryptor seems to expect JSON.

**Comment by andrei-a-papou** [comment]
OK, my bad, found the *.properties file, re-testing

**Comment by andrei-a-papou** [comment]
Awesome, seems to work great!

**Comment by Tiefkuehlpizze** [comment]
Perfect! Thanks for the feedback! I've added a note about custom salts to the readme. As far as I remember, Neo Backup always uses the fallback salt "oandbackupx". It's configurable, but the latest 8.0.0-alpha11 still doesn't offer the option in the UI yet. It would be another potentially breaking change or would need some compatibility code or would at least need some idea how the salt is stored.
I'm glad I could help and share the knowledge about Neo Backup's internals and encryption. :grinning:
