### ISSUE TITLE
Can we get the password from a file, rather than CLI?

### ISSUE THREAD

**Issue by andrei-a-papou** [Tiefkuehlpizze/OABXDecrypt#3]
This would of course improve security.

**Comment by andrei-a-papou** [comment]
With v1.1 the -passfile option seems to work, but reading password from a environment variable throws this error:

```
13:09:03.461 DEBUG: Trying to retrieve password from environment variable NB_PASSWORD
Exception in thread "main" java.lang.IllegalArgumentException: No password option set
	at tkp.App.retrievePassword(App.java:171)
	at tkp.App.main(App.java:183)
```

I've double-checked and the variable NB_BACKUP is set.

**Comment by Tiefkuehlpizze** [comment]
Try to set `NB_PASSWORD` as it's writing. :)

**Comment by andrei-a-papou** [comment]
Yes, sorry, it actually was `NB_PASSWORD` in the shell, the mistake was only in the comment above :)

Checked again, same error.

**Comment by Tiefkuehlpizze** [comment]
My fault: `read -s NB_PASSWORD` reads a value into a variable, but does not make it available as environment variable. What's missing is `export NB_PASSWORD` after the read call.

**Comment by andrei-a-papou** [comment]
Perfect, works now!
